object Versions {
    const val coreKtx = "1.10.0"
    const val lifecycleRuntimeKtx = "2.6.1"
    const val activityCompose = "1.7.0"
    const val composeBom = "2023.03.00"
    const val jUnit1  = "1.1.5"
    const val jUnit4 = "4.13.2"
    const val espressoCore  = "3.5.1"
    const val appCompat = "1.6.1"
    const val material = "1.8.0"
    const val hilt = "2.48"
    const val hiltCompiler = "1.0.0-alpha01"
    const val hiltNavigationCompose = "1.0.0"
    const val retrofit = "2.9.0"
    const val okhttp = "4.11.0"
    const val gsonConverter = "2.9.0"
    const val moshi = "1.13.0"
    const val moshiConverter = "2.9.0"
    const val loggingInterceptor = "4.8.1"
    const val coroutines = "1.7.3"
    const val coil = "2.2.0"

}